INSERT INTO CASH_CARD(ID, AMOUNT, OWNER) VALUES (99, 123.45, 'John Doe');
INSERT INTO CASH_CARD(ID, AMOUNT, OWNER) VALUES (100, 1.00, 'Jane Doe');
INSERT INTO CASH_CARD(ID, AMOUNT, OWNER) VALUES (101, 150.00, 'John Smith');